---
from:
  - v2/params/pods

test:
  param1: pipelines

params:
  pipelines:
    state:
      development:
        params:
          pods:
          - from: .params.pods.state.development
      staging:
        params:
          pods:
          - from: .params.pods.state.staging

      stable:
        params:
          pods:
          - from: .params.pods.state.stable

    release:
      build:
        params:
          pods:
          - from: .params.pods.release.build

      deploy:
        preprod:
          params:
            pods:
            - from: .params.pods.release.deploy.preprod

        prod:
          params:
            pods:
            - from: .params.pods.release.deploy.prod
