---
params:
  containers:
    common:
      params:
        image: michaeltigr/zebra-build-php-drush-docman:0.0.91
      build:
        params:
          image: michaeltigr/zebra-build-php-drush-docman:0.0.91
        none:
          params:
           execute: false
        release:
          params:
            name: build-release
            blocks:
            - actions:
              - from: .params.actions.Docman.${context.environment}.releaseBuild
        deliverables:
          params:
            name: build-deliverables
            blocks:
            - actions:
              - from: .params.actions.Docman.${context.environment}.build
        single:
          params:
            name: build-single
            blocks:
            - actions:
              - from: .params.actions.YamlFileHandler.build
      deploy:
        params:
          image: michaeltigr/zebra-deploy-ansible:2.3.2.0
        none:
          params:
            execute: false
        commands:
          params:
            name: deploy-commands
            blocks:
            - actions:
              - from: .params.actions.Commands.deploy.${context.environment}.execute
        ansible:
          params:
            name: deploy-ansible
            blocks:
            - actions:
              - from: .params.actions.Ansible.${context.environment}.deploy
        ansible_git:
          params:
            name: deploy-ansible-git
            blocks:
            - actions:
              - from: .params.actions.Ansible.${context.environment}.deployWithAnsistranoGit
      operations:
        params:
          image: michaeltigr/zebra-operations-druflow:0.1.4
        none:
          params:
            execute: false
        druflow:
          params:
            name: operations-druflow
            blocks:
            - actions:
              - from: .params.actions.Druflow.${context.environment}.operations
        commands:
          params:
            name: operations-commands
            blocks:
            - actions:
              - from: .params.actions.Commands.operations.${context.environment}.execute
        yaml:
          params:
            name: operations-yaml
            blocks:
            - actions:
              - from: .params.actions.YamlFileHandler.${context.environment}.operations
      artifact:
        params:
          image: michaeltigr/zebra-build-php-drush-docman:0.0.91
        none:
          params:
            execute: false
        git:
          params:
            name: artifact
            blocks:
            - actions:
              - from: .params.actions.PipelineController.${context.environment}.retrieveArtifact
                artifactHandler:
                  handler: GitArtifact
                  method: retrieve
      test:
        none:
          params:
            execute: false
