from:
  - v2/params/jobs

jobs:
  release-deploy-prod:
    from: .params.jobs.release.deploy.prod
    context:
      cap_environment: production
      cap_branch: BRANCH=${context.env.release}
      cap_options: ""
