---
from:
  - v2/params/containers

test:
  param1: pods

params:
  pods:
    state:
      development:
        params:
          containers:
          - from: .params.containers.common.build.${context.container_types.build.development.type}.development
          - from: .params.containers.common.artifact.${context.container_types.artifact.development.type}.development
          - from: .params.containers.common.deploy.${context.container_types.deploy.development.type}.development
          - from: .params.containers.common.operations.${context.container_types.operations.development.type}.development
          - from: .params.containers.common.test.${context.container_types.test.development.type}.development
      staging:
        params:
          containers:
          - from: .params.containers.common.build.${context.container_types.build.staging.type}.staging
          - from: .params.containers.common.artifact.${context.container_types.artifact.staging.type}.staging
          - from: .params.containers.common.deploy.${context.container_types.deploy.staging.type}.staging
          - from: .params.containers.common.operations.${context.container_types.operations.staging.type}.staging
          - from: .params.containers.common.test.${context.container_types.test.staging.type}.staging
      stable:
        params:
          containers:
          - from: .params.containers.common.build.${context.container_types.build.stable.type}.stable

    release:
      build:
        params:
          containers:
            - from: .params.containers.common.build.${context.container_types.build.release.build.type}.release.build

      deploy:
        preprod:
          params:
            containers:
            - from: .params.containers.common.artifact.${context.container_types.artifact.release.deploy.preprod.type}.release.deploy.preprod
            - from: .params.containers.common.deploy.${context.container_types.deploy.release.deploy.preprod.type}.release.deploy.preprod
            - from: .params.containers.common.operations.${context.container_types.operations.release.deploy.preprod.type}.release.deploy.preprod

        prod:
          params:
            containers:
            - from: .params.containers.common.artifact.${context.container_types.artifact.release.deploy.prod.type}.release.deploy.prod
            - from: .params.containers.common.deploy.${context.container_types.deploy.release.deploy.prod.type}.release.deploy.prod
            - from: .params.containers.common.operations.${context.container_types.operations.release.deploy.prod.type}.release.deploy.prod
